global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "gateway"
    metrics_path: /metrics
    static_configs:
      - targets: ["api-gateway:8000"]

  - job_name: "auth-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["auth-service:8000"]

  - job_name: "orders-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["orders-service:8000"]

  - job_name: "payments-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["payments-service:8000"]

  - job_name: "ai-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["analytics-service:8000"]

  - job_name: "trust-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["trust-service:8000"]

  - job_name: "celery-worker"
    metrics_path: /metrics
    static_configs:
      - targets: ["worker:9100"]

  - job_name: "redis-exporter"
    metrics_path: /metrics
    static_configs:
      - targets: ["redis-exporter:9121"]

  - job_name: "cadvisor"
    metrics_path: /metrics
    static_configs:
      - targets: ["cadvisor:8080"]

